"""add_streak_fields_to_user

Revision ID: ac90a25faeca
Revises: 
Create Date: 2026-03-10 13:33:42.091660
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
"""add_streak_fields_to_user

Revision ID: ac90a25faeca
Revises: 
Create Date: 2026-03-10 13:33:42.091660
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'ac90a25faeca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adding new columns for Daily Streak feature
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_streak_claimed_at', sa.DateTime(timezone=True), nullable=True))
    
    # We also added STREAK_REWARD to the TransactionType enum. 
    # Since native_enum=False was used, it's just a check constraint or string.
    # No explicit migration needed for the Enum if native_enum=False at the DB level, 
    # but let's ensure the column can accept the new value if there are constraints.
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'aura_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'username',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'premium_expires_at')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'last_streak_claimed_at')
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'firebase_uid')
    op.add_column('posts', sa.Column('aura', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.alter_column('posts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('posts', 'image_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('posts', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('posts', 'aura_score')
    op.drop_column('posts', 'content')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_table('followers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('following_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='followers_pkey')
    )
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_mission_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_aura_transactions_to_user_id'), table_name='aura_transactions')
    op.drop_index(op.f('ix_aura_transactions_post_id'), table_name='aura_transactions')
    op.drop_index(op.f('ix_aura_transactions_id'), table_name='aura_transactions')
    op.drop_index(op.f('ix_aura_transactions_from_user_id'), table_name='aura_transactions')
    op.drop_table('aura_transactions')
    op.drop_index(op.f('ix_missions_user_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
